version: '3.8'
services:
  comfyui:
    build: .  # Utilise le Dockerfile dans le répertoire courant
    ports:
      - "8188:8188"  # Redirection du port 8188 de l'hôte vers le conteneur
    volumes:
      - ./output:/app/comfyui/output
      - ./input:/app/comfyui/input
      - ./models/checkpoints:/app/comfyui/models/checkpoints
      - ./models/clip:/app/comfyui/models/clip
      - ./models/clip_vision:/app/comfyui/models/clip_vision
      - ./models/controlnet:/app/comfyui/models/controlnet
      - ./models/diffusers:/app/comfyui/models/diffusers
      - ./models/embeddings:/app/comfyui/models/embeddings
      - ./models/gligen:/app/comfyui/models/gligen
      - ./models/hypernetworks:/app/comfyui/models/hypernetworks
      - ./models/loras:/app/comfyui/models/loras
      - ./models/photomaker:/app/comfyui/models/photomaker
      - ./models/style_models:/app/comfyui/models/style_models
      - ./models/unet:/app/comfyui/models/unet
      - ./models/upscale_models:/app/comfyui/models/upscale_models
      - ./models/vae:/app/comfyui/models/vae
      - ./models/vae_approx:/app/comfyui/models/vae_approx
    networks:
      - internal_network
    cap_add:
      - NET_ADMIN  # Pour gérer les règles réseau
    dns:
      - 127.0.0.1  # Bloque l'accès Internet en empêchant la résolution DNS
    command: |
      bash -c "
      iptables -I OUTPUT -o eth0 -j DROP;  # Bloque les connexions sortantes
      exec /app/entrypoint.sh --listen 0.0.0.0 --port 8188 --preview-method auto"  # Lance le service

networks:
  internal_network:
    driver: bridge
